### ISSUE TITLE
But what if you don't have a version of QUARTUS to program Cyclone II?

### ISSUE THREAD

**Issue by Bazmundi** [douggilliland/EP2C5-Cyclone-II-Mini-Board#1]
I replaced my PC and forgot to move my Quartus 11.1 over (the latest really for Cyclone II).   So, I have no means of programming the device unless there is an open source equivalent.  Have you a suggestion for an open source equivalent environment for programming Cyclone II please?

**Comment by douggilliland** [comment]
You should be able to download Cyclone from Intel. Version 13.0 Service Pack 1 is still on the site and it supports Cyclone II parts.

https://www.intel.com/content/www/us/en/programmable/downloads/download-center.html

**Comment by Bazmundi** [comment]
> You should be able to download Cyclone from Intel. Version 13.0 Service Pack 1 is still on the site and it supports Cyclone II parts.
> 
> https://www.intel.com/content/www/us/en/programmable/downloads/download-center.html

DOH! Yeah, I did eventually sort that out, once I trawled the Intel pages and came across a table of chips2versions.   Lesson learned ;)

Thanks for the patient response.
